config_dict= {
"vision_encoder": {
    "name": "videomamba_middle",
    "img_size": 224,
    "patch_size": 16,
    "depth": 32,
    "embed_dim": 576,
    "drop_path_rate": 0.25,
    "ssm_cfg": None,
    "norm_epsilon": 1e-5,
    "fused_add_norm": True,
    "rms_norm": True,
    "residual_in_fp32": True,
    "bimamba": True,
    "pool_type": "cls+avg",
    "kernel_size": 1,
    "num_frames": 8,
    "ckpt_num_frame": 8,
    "use_checkpoint": False,
    "checkpoint_num": 0,
    "clip_decoder_embed_dim": 576,
    "clip_output_dim": 512,
    "clip_norm_type": "l2",
    "clip_return_layer": 1,
    "clip_student_return_interval": 1,
    "pretrained": "hf://OpenGVLab/VideoMamba/videomamba_m16_25M_f8_res224.pth",
    "clip_teacher": "clip_b16",
    "clip_img_size": 224,
    "clip_return_interval": 1,
    "video_mask_type": "attention",
    "video_mask_ratio": 0.8,
    "video_double_mask_ratio": 0.0,
    "image_mask_type": "attention",
    "image_mask_ratio": 0.5,
    "image_double_mask_ratio": 0.0,
    "keep_temporal": True,
    'tubelet_size':1,
},
    'compile_model':False,
    'device':'cuda',
    'use_half_precision': False,
    'use_bf16': False
}
